pipeline {

    agent {
        label 'java_21'
    }

    environment {
        NUMBER = 3
    }

    stages {

        stage('stage-1') {
            steps {
                echo "doing mvn clean"
                echo "doing mvn package"
                echo "NUMBER = ${NUMBER}"
            }
        }

        stage('stage-2') {
            environment {
                NUMBER = 6
            }
            steps {
                echo "building docker image"
                echo "NUMBER = ${NUMBER}"
            }
        }

        stage('stage-3') {
            steps {
                echo "pushing docker image"
                echo "NUMBER = ${NUMBER}"
            }
        }

    }

    post {
        always {
            echo "doing clean up"
        }
    }

}