version: "3"
services:
  jenkins:
    image: jenkins/jenkins:2.486-jdk21
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./volumes/master:/var/jenkins_home
    environment:
      - JAVA_OPTS="-Dhudson.model.DirectoryBrowserSupport.CSP="